"""expand all size

Revision ID: 230e6533c7a4
Revises: 6476f99428c5
Create Date: 2020-04-10 11:47:10.682561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230e6533c7a4'
down_revision = '6476f99428c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
