"""fix bugs

Revision ID: 2b19d10e3dde
Revises: 230e6533c7a4
Create Date: 2020-04-10 12:04:03.621115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b19d10e3dde'
down_revision = '230e6533c7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'author',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('track', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('track', 'author',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
