"""add album column

Revision ID: 6476f99428c5
Revises: 9879189f5c3c
Create Date: 2020-04-09 12:19:53.179877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476f99428c5'
down_revision = '9879189f5c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('album', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'album')
    # ### end Alembic commands ###
