"""change the size of the song's name and author

Revision ID: 9879189f5c3c
Revises: 5eb2a7733e04
Create Date: 2020-04-09 10:17:32.061989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9879189f5c3c'
down_revision = '5eb2a7733e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
